// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow for generating smart suggestions to optimize Firebase data and metrics using AI.
 *
 * - generateFirebaseInsights - A function that generates smart suggestions for Firebase data optimization.
 * - GenerateFirebaseInsightsInput - The input type for the generateFirebaseInsights function.
 * - GenerateFirebaseInsightsOutput - The return type for the generateFirebaseInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFirebaseInsightsInputSchema = z.object({
  firebaseDataSummary: z
    .string()
    .describe('A summary of the Firebase project data and metrics.'),
});
export type GenerateFirebaseInsightsInput = z.infer<typeof GenerateFirebaseInsightsInputSchema>;

const GenerateFirebaseInsightsOutputSchema = z.object({
  suggestions: z
    .string()
    .describe('AI-generated suggestions for optimizing Firebase data and metrics.'),
});
export type GenerateFirebaseInsightsOutput = z.infer<typeof GenerateFirebaseInsightsOutputSchema>;

export async function generateFirebaseInsights(
  input: GenerateFirebaseInsightsInput
): Promise<GenerateFirebaseInsightsOutput> {
  return generateFirebaseInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFirebaseInsightsPrompt',
  input: {schema: GenerateFirebaseInsightsInputSchema},
  output: {schema: GenerateFirebaseInsightsOutputSchema},
  prompt: `You are an AI assistant specializing in providing actionable insights for Firebase projects.

  Based on the provided Firebase project data summary, generate smart suggestions to optimize data and metrics.

  Firebase Data Summary: {{{firebaseDataSummary}}}

  Suggestions:
  `,config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const generateFirebaseInsightsFlow = ai.defineFlow(
  {
    name: 'generateFirebaseInsightsFlow',
    inputSchema: GenerateFirebaseInsightsInputSchema,
    outputSchema: GenerateFirebaseInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
