// This is an autogenerated file from Firebase Studio.

import { initializeApp, getApp, getApps, type FirebaseApp } from "firebase/app";
import { getFirestore, type Firestore } from "firebase/firestore";

let app: FirebaseApp | null = null;
let db: Firestore | null = null;
let firebaseInitializationError: string | null = null;

// Check if NEXT_PUBLIC_FIREBASE_PROJECT_ID is available. 
// This is crucial for Firebase to initialize.
const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;

if (projectId && typeof projectId === 'string' && projectId.trim() !== '') {
  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: projectId,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    // measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID, // Optional
  };

  // Ensure all required config values are present (optional: add more checks if needed)
  if (firebaseConfig.apiKey && firebaseConfig.authDomain && firebaseConfig.appId) {
    try {
      if (getApps().length === 0) {
        app = initializeApp(firebaseConfig);
      } else {
        app = getApp();
      }
      db = getFirestore(app);
    } catch (e: any) {
      console.error("Firebase initialization error:", e);
      firebaseInitializationError = e.message || "Failed to initialize Firebase. Check your configuration values in .env.local.";
      // Ensure app and db are null if initialization failed
      app = null;
      db = null;
    }
  } else {
    firebaseInitializationError = "One or more Firebase configuration values (apiKey, authDomain, appId) are missing in .env.local. Please check your Firebase project settings.";
    app = null;
    db = null;
  }
} else {
  firebaseInitializationError = "Firebase Project ID (NEXT_PUBLIC_FIREBASE_PROJECT_ID) is not configured. Please set it up in your .env.local file and restart the server.";
  app = null;
  db = null;
}

export { app, db, firebaseInitializationError };
