
// This is an autogenerated file from Firebase Studio.

import { initializeApp, getApp, getApps, type FirebaseApp } from "firebase/app";
import { getFirestore, type Firestore } from "firebase/firestore";
import { 
  getAuth, 
  type Auth, 
  GoogleAuthProvider, 
  signInWithPopup, 
  signOut as firebaseSignOut // Renamed to avoid conflict
} from "firebase/auth";

let app: FirebaseApp | null = null;
let db: Firestore | null = null;
let auth: Auth | null = null;
let firebaseInitializationError: string | null = null;

const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
const apiKey = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
const authDomain = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
const storageBucket = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
const messagingSenderId = process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
const appId = process.env.NEXT_PUBLIC_FIREBASE_APP_ID;

// Log the environment variables to help debug
console.log("[Firebase Setup] Attempting to load NEXT_PUBLIC_FIREBASE_PROJECT_ID:", projectId);
console.log("[Firebase Setup] Attempting to load NEXT_PUBLIC_FIREBASE_API_KEY:", apiKey ? "Found" : "MISSING or Empty");
console.log("[Firebase Setup] Attempting to load NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:", authDomain ? "Found" : "MISSING or Empty");
console.log("[Firebase Setup] Attempting to load NEXT_PUBLIC_FIREBASE_APP_ID:", appId ? "Found" : "MISSING or Empty");


if (projectId && typeof projectId === 'string' && projectId.trim() !== '') {
  const firebaseConfig = {
    apiKey: apiKey,
    authDomain: authDomain,
    projectId: projectId,
    storageBucket: storageBucket,
    messagingSenderId: messagingSenderId,
    appId: appId,
  };

  // CRITICAL LOG: This shows the config object JUST BEFORE initialization.
  console.log("%c[Firebase Setup] CRITICAL CHECK - USING THIS CONFIG FOR INITIALIZATION:", "color: red; font-weight: bold;", {
    apiKey: firebaseConfig.apiKey ? 'Exists' : 'MISSING',
    authDomain: firebaseConfig.authDomain || 'MISSING',
    projectId: firebaseConfig.projectId, // This is the most important for auth/unauthorized-domain
    appId: firebaseConfig.appId ? 'Exists' : 'MISSING',
    storageBucket: firebaseConfig.storageBucket || 'Not set',
    messagingSenderId: firebaseConfig.messagingSenderId || 'Not set'
  });

  if (firebaseConfig.apiKey && firebaseConfig.authDomain && firebaseConfig.appId) {
    try {
      if (getApps().length === 0) {
        app = initializeApp(firebaseConfig);
        console.log("[Firebase Setup] Firebase App Initialized successfully with Project ID:", firebaseConfig.projectId);
      } else {
        app = getApp();
        console.log("[Firebase Setup] Existing Firebase App Retrieved for Project ID:", app.options.projectId);
      }
      db = getFirestore(app);
      auth = getAuth(app); 
      console.log("[Firebase Setup] Firestore and Auth services obtained.");
    } catch (e: any) {
      console.error("[Firebase Setup] Firebase initialization error during initializeApp() or getAuth():", e);
      firebaseInitializationError = `Failed to initialize Firebase services. Error: ${e.message}. Check console & .env.local. Ensure project ID ('${projectId}') from env matches the project where domains are authorized. Actual error: ${e.code || e.message}`;
      app = null;
      db = null;
      auth = null;
    }
  } else {
    let missingKeys = [];
    if (!firebaseConfig.apiKey) missingKeys.push("NEXT_PUBLIC_FIREBASE_API_KEY");
    if (!firebaseConfig.authDomain) missingKeys.push("NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN");
    if (!firebaseConfig.appId) missingKeys.push("NEXT_PUBLIC_FIREBASE_APP_ID");
    
    firebaseInitializationError = `Firebase config incomplete for Project ID '${projectId}'. Missing/empty critical environment variables: ${missingKeys.join(', ')} in .env.local. Please check Firebase project settings.`;
    console.error("[Firebase Setup] Error:", firebaseInitializationError);
    app = null;
    db = null;
    auth = null;
  }
} else {
  firebaseInitializationError = "CRITICAL ERROR: Firebase Project ID (NEXT_PUBLIC_FIREBASE_PROJECT_ID) is MISSING or empty in .env.local. Firebase cannot be initialized. Please set it up and restart the server.";
  console.error("[Firebase Setup] Error:", firebaseInitializationError);
  app = null;
  db = null;
  auth = null;
}

export { 
  app, 
  db, 
  auth, 
  firebaseInitializationError, 
  GoogleAuthProvider, 
  signInWithPopup,      
  firebaseSignOut       
};

